### ISSUE TITLE
Verify this works for multiple-passenger itineraries

### ISSUE THREAD

**Issue by DavidWittman** [DavidWittman/serverless-southwest-check-in#19]

**Comment by DavidWittman** [comment]
It doesn't. We either need to scrape each of the passengers from the email subject and then execute a step function for each, or retrieve the passenger list in `schedule_check_in` and populate that object in the event object.

``` yaml
confirmation_number: ABC123
check_in_times:
  next: 123
  remaining:
    - 456
passengers:
  - George Bush
  - Barbara Bush
```
